name: ci_check_duration
# 
on: [workflow_dispatch]

jobs:

  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master 
        uses: actions/checkout@v2

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: check_duration
          registry: ghcr.io/orgs/webjets
          tags: stage
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
